version: "3.4"
services:
  e-zone-user-app:build:
    stdin_open: true
    build:
      context: .
      dockerfile: dockerfile
    expose:
      - 8080
    ports:
      - 8080:80
    environment: -CHOKIDAR_USEPOLLING=true
